//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListManager
{
    using System;
    using System.Collections.Generic;

    public partial class Enrollment2
    {
        public int EnrollmentId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string SemesterId { get; set; }
    }
}
