//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListManager
{
    using System;
    using System.Collections.Generic;

    public partial class SemesterYear2
    {
        public int SemesterYearId { get; set; }
    }
}
